:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_json)).
:- use_module(library(http/http_parameters)).
:- use_module(library(http/http_client)).
:- use_module(library(http/http_json)).

% Define una ruta para recibir la salida del archivo TypeScript
:- http_handler(root(test_output), handle_test_output, [method(post)]).

% Manejador para recibir la salida del archivo TypeScript
handle_test_output(Request) :-
    http_read_json_dict(Request, Data), % Lee los datos enviados en formato JSON
    get_time(TimeStamp),
    format_time(atom(TimeStampStr, '%Y-%m-%d %H:%M:%S', TimeStamp),
    string_concat("// Generated by Prolog OFS 1.5 transpiler ", TimeStampStr, Comment1),
    string_concat(Comment1, Data.content, ModifiedData), % Agrega el comentario al inicio
    Reply = json{content: ModifiedData}, % Prepara la respuesta con los datos modificados
    reply_json(Reply)).

% Inicia el servidor en un puerto específico
server(Port) :-
    http_server(http_dispatch, [port(Port)]).

% Inicialización
:- initialization
    (current_prolog_flag(argv, [SPort | _]) -> true ; SPort='8000'),
    atom_number(SPort, Port),
    server(Port).

